version: '3.8'
services:
  backend:
    image: econome
    pull_policy: never
    container_name: econome
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.12
    container_name: econome-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data: